- app/Http/Controllers/Api/AuthController.php
- app/Models/User.php
- bootstrap/app.php
- composer.json
- composer.lock
- config/sanctum.php
- database/migrations/2025_01_29_163918_create_personal_access_tokens_table.php
- database/seeders/DatabaseSeeder.php
- database/seeders/UserSeeder.php
- routes/api.php
This pull request introduces authentication using Laravel Sanctum and includes several changes to support this new feature. The most important changes include adding the `AuthController`, updating the `User` model, configuring Sanctum, and creating the necessary database migration and seeders.
Authentication feature implementation:
* [`app/Http/Controllers/Api/AuthController.php`](diffhunk://#diff-ad6f5ce68221913af0e24dc74b618133cc1f3d1637f388a6bb3f9fe5f31947e0R1-R30): Added `AuthController` with `login` and `logout` methods to handle user authentication.
* [`app/Models/User.php`](diffhunk://#diff-37a2d7d879a7de3f7d73b2975cd22be9f41ec10c334a0dda9ad1e869332e4ecbR9-R13): Updated the `User` model to use the `HasApiTokens` trait from Laravel Sanctum.
* …
> feat: implement API authentication with Laravel Sanctum

- app/Http/Middleware/RoleMiddleware.php
- database/migrations/0001_01_01_000000_create_users_table.php
- database/seeders/UserSeeder.php
- resources/ts/components/Admin/Dashboard/Stats.tsx
- resources/ts/components/Login/LoginForm.tsx
- resources/ts/contexts/AuthContext.tsx
- routes/api.php
This pull request includes several changes to the codebase, primarily focusing on implementing role-based access control, updating the user roles to be string-based, and enhancing the admin dashboard statistics. Here are the most important changes:
* Added `RoleMiddleware` to handle role-based access control for routes. This middleware checks if the user's role matches the required role and returns a 403 Unauthorized response if it does not. (`app/Http/Middleware/RoleMiddleware.php`)
* Changed the `role` field in the `users` table from an integer to a string with a default value of 'customer'. (`database/migrations/0001_01_01_000000_create_users_table.php`)
* Updated the `UserSeeder` to use string values for roles ('admin', 'worker', 'customer') instead of integers. …
> feat: add api middleware for roles and add dashboard stats

- app/Http/Controllers/LandingController.php
- database/migrations/2025_02_04_174010_create_landing_form_table.php
- lang/ca/landings/landing10.php
- lang/en/landings/landing10.php
- lang/es/landings/landing10.php
- resources/views/landings/landing10.blade.php
- routes/web.php
This pull request introduces several changes to enhance form handling, database schema, and localization support for a landing page. The most important changes include the addition of form validation and saving logic, updates to the database schema to allow nullable fields, and the inclusion of localization files for multiple languages.
* [`app/Http/Controllers/LandingController.php`](diffhunk://#diff-3eaa8a20c34668a2a5c7fa5e355631ec940d9841311359def89a413b3212c31eL36-R49): Added validation for form inputs and logic to save the form data to the database.
* [`database/migrations/2025_02_04_174010_create_landing_form_table.php`](diffhunk://#diff-80ece7477cbf70618c1edb91f9ab66aa17629835266633092fb88e789bdc79e7L16-R19): Updated the migration to allow `name`, `phone`, and `message` fields to …
> feat: add landing 10

- resources/views/landings/landing1.blade.php
Co-authored-by: Chuck.D.Norris <boveoriol@gmail.com>
> fix: add vite to landing 1

- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/pages/Admin/Settings/Tree Types/Create.tsx
- resources/ts/pages/Admin/Settings/Tree Types/Edit.tsx
- resources/ts/pages/Admin/Settings/Tree Types/TreeTypes.tsx
- resources/ts/pages/Admin/Settings/Users/Create.tsx
- resources/ts/pages/Admin/Settings/Users/Edit.tsx
- resources/ts/pages/Admin/Settings/Users/Users.tsx
This pull request includes significant updates to the localization files for Catalan, English, and Spanish languages, as well as modifications to the `CreateTreeType` component in the `resources/ts/pages/Admin/Settings/Tree Types/Create.tsx` file. The primary focus is on restructuring and enhancing the user interface text and validation messages.
Localization updates:
* [`resources/ts/config/i18n/ca.json`](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85L90-R122): Added nested structures for user, tree type, and general messages, including success and error messages, and form validation texts. [[1]](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85L90-R122) [[2]](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f …
> Refactor(lang) :lang structure and the views

- app/Http/Controllers/Api/Admin/TaskTypeController.php
- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/pages/Admin/Settings/Task Types/Create.tsx
- resources/ts/pages/Admin/Settings/Task Types/Edit.tsx
- resources/ts/pages/Admin/Settings/Task Types/TaskTypes.tsx
- resources/ts/routes/AdminRoutes.tsx
- routes/api.php
Implement create, read, update, and delete operations for task types, along with UI enhancements and language support.
> Add CRUD functionality for task types

- app/Http/Controllers/Api/Admin/ContractController.php
Introduce full CRUD functionality for contracts, allowing for the creation, retrieval, updating, and deletion of contract records.
> Implement CRUD operations for contracts in ContractController

- .github/workflows/deploy-production.yml
This pull request includes a change to the deployment workflow configuration file to improve the migration process.
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94L60-R60): Changed the migration command to use the `--step` option instead of `--seed` to allow for more granular control over the migration process.
> chore: update migration command to use --step option for better control

- .github/workflows/deploy-production.yml
This pull request includes updates to the deployment workflow in the `.github/workflows/deploy-production.yml` file. The changes focus on improving file permissions, optimizing dependency installation, and ensuring the correct user executes commands.
Improvements to file permissions:
* Updated the `rsync` command to use a more concise `--exclude` syntax and added the `--chown` option to set ownership during file transfer.
* Modified the `chmod` and `chown` commands to set more restrictive permissions on specific directories and ensure consistent ownership.
Optimizations to dependency installation:
* Replaced `npm install` with `npm ci --legacy-peer-deps` to ensure a clean and reproducible installation of Node.js dependencies.
Execution of commands by the correct user:
* Ensured that `php …
> fix: streamline deployment script

- .github/workflows/deploy-production.yml
- resources/ts/pages/Admin/WorkOrders/WorkOrders.tsx
This pull request includes several changes to the deployment workflow and the admin work orders page. The most important changes include modifying the deployment script to fix permissions and improve efficiency, and updating the work orders page to disable the edit button when no contract is selected.
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94L30-R43): Added a step to fix permissions for Laravel by changing ownership and permissions of specific directories. This ensures proper access and functionality of the application on the server.
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94L30-R43): Modified the rsync command to …
> Fix: workorder contracts

- resources/ts/middlewares/AdminProtectedRoute.tsx
- resources/ts/routes/AdminRoutes.tsx
This pull request includes changes to the `AdminProtectedRoute` middleware and the `AdminRoutes` configuration to enhance navigation handling and simplify the routes structure.
Enhancements to navigation handling:
* [`resources/ts/middlewares/AdminProtectedRoute.tsx`](diffhunk://#diff-75bc40ef3ad30cadd7c7a7488b0417f5179068ab4ad05b2b4309e6d8526c8598L1-R12): Added `useLocation` import and updated the `Navigate` component to include the current location in the state.
Simplification of routes structure:
* [`resources/ts/routes/AdminRoutes.tsx`](diffhunk://#diff-b0d509f134a8f2eef094f42cf905df35ec7948496ad63e7d67846df17d9f38c2L41-R41): Replaced multiple `Navigate` elements to use the `replace` prop for better navigation handling. [[1]](diffhunk://#diff-b0d509f134a8f2eef094f42cf905df35ec7948496ad …
> feat: enhance admin routing with improved navigation and loading states

- app/Http/Controllers/Api/Admin/ResourceController.php
- app/Http/Requests/StoreResourceRequest.php
- app/Http/Requests/UpdateResourceRequest.php
- app/Models/Resource.php
- database/migrations/2025_03_24_155555_add_columns_to_resources.php
- database/seeders/ResourceSeeder.php
- resources/ts/config/i18n/en.json
- resources/ts/pages/Admin/Settings/Resources/Create.tsx
- resources/ts/pages/Admin/Settings/Resources/Edit.tsx
- resources/ts/pages/Admin/Settings/Resources/Resources.tsx
- resources/ts/types/Resource.ts
Introduce unit cost and unit name fields in the resources model, update validation rules, and enhance resource creation and editing forms. Update resource display to include these new fields and ensure proper internationalization support.
> Add unit cost and unit name fields to resources model and forms

- app/Http/Controllers/Api/Admin/WorkOrderController.php
- app/Http/Controllers/Api/Admin/WorkReportController.php
- resources/ts/pages/Admin/WorkReport.tsx
- routes/api.php
Introduce a new endpoint for updating work order status and improve validation for work reports. Additionally, implement logic to calculate work order status based on task progress.
> Add status update functionality for work orders and enhance work report validation

- app/Http/Controllers/Api/Admin/StatisticsController.php
- app/Http/Controllers/Api/Admin/WorkReportController.php
- app/Models/WorkReport.php
- database/seeders/WorkOrderSeeder.php
- database/seeders/WorkReportResourceSeeder.php
- database/seeders/WorkReportSeeder.php
- resources/ts/config/i18n/en.json
- resources/ts/pages/Admin/Statistics.tsx
Refactor the WorkReport model to correct relationship naming and update seeder data for consistency. Enhance localization strings and adjust work report resource associations. Statistics has a new block.
> Update WorkReport model relationships and seeder data

- app/Http/Controllers/Api/Admin/ContractUserController.php
- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/layouts/AdminLayout.tsx
- resources/ts/pages/Admin/Workers.tsx
- routes/api.php
This pull request introduces new functionality for managing workers assigned to contracts in the admin section. The changes include updates to the backend controller, new routes, and a new front-end page for handling these assignments. Additionally, translations for the new functionality are added for multiple languages.
Backend updates:
* [`app/Http/Controllers/Api/Admin/ContractUserController.php`](diffhunk://#diff-433078b59582b94961c12fe8b92de25c9283286e0a5847108e19c9866b3bbcccL13-R21): Modified the `index` and `store` methods to handle listing and assigning users to contracts. Removed unused methods. [[1]](diffhunk://#diff-433078b59582b94961c12fe8b92de25c9283286e0a5847108e19c9866b3bbcccL13-R21) [[2]](diffhunk://#diff-433078b59582b94961c12fe8b92de25c9283286e0a5847108e19c9866b3bbcccL44-R …
> feat(contract-workers): assign workers to contract

- app/Http/Controllers/Api/Admin/ElementController.php
- resources/ts/api/service/mapService.ts
- resources/ts/components/Admin/Inventory/ElementDetailPopup.tsx
- resources/ts/components/Admin/Inventory/SaveElementForm.tsx
- resources/ts/components/Map.tsx
- resources/ts/store/slice/incidentSlice.ts
- resources/ts/store/store.ts
This pull request includes several changes to the `MapService` class, improvements to the `ElementDetailPopup` and `SaveElementForm` components, and the addition of a new `incidentSlice` for handling incidents. The most important changes include modifying the `MapService` class to improve code readability and functionality, updating the `ElementDetailPopup` to use a new async action, and adding a new Redux slice for incident management.
Improvements to `MapService` class:
* [`resources/ts/api/service/mapService.ts`](diffhunk://#diff-087dbd3207f44a8047f8087446874c65e1b1fc383c1f0096368edbb83f18925aL56-L67): Refactored the `enableDraw` and `enableSingleClick` methods to remove unnecessary lines and improve readability. [[1]](diffhunk://#diff-087dbd3207f44a8047f8087446874c65e1b1fc383c1f0096368 …
> Fix: bugs in map

- app/Http/Controllers/Api/Admin/WorkReportController.php
- app/Http/Controllers/Api/Worker/IndexController.php
- app/Http/Controllers/Api/Worker/ResourceController.php
- app/Models/User.php
- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/layouts/WorkerLayout.tsx
- resources/ts/pages/Admin/WorkReport.tsx
- resources/ts/pages/Worker/Dashboard.tsx
- resources/ts/pages/Worker/Index.tsx
- resources/ts/routes/WorkerRoutes.tsx
- routes/api.php
This pull request includes several significant changes to the `app/Http/Controllers/Api` directory and translations in the `resources/ts/config/i18n` directory. The most important changes involve adding new controllers for worker-related operations, updating work order statuses, and adding new translations for worker-related features.
* [`app/Http/Controllers/Api/Worker/IndexController.php`](diffhunk://#diff-c4734b09ba7238e57863de5f7bfa5ec1bc51e7fa4afdd035a3a93869939a2cdcR1-R257): Added a new controller to handle listing work orders, updating task statuses, recalculating work order statuses, and creating work reports.
* [`app/Http/Controllers/Api/Worker/ResourceController.php`](diffhunk://#diff-167a71cd4b9fbba6f3327ec1b517a27b92e6f0d07f8260f11083d8b1c957e95bR1-R40): Added a new controller …
> Feat: workers

- app/Http/Controllers/Api/Admin/AccountController.php
- app/Http/Controllers/Api/AuthController.php
- bootstrap/app.php
- resources/ts/api/axiosClient.ts
- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/hooks/useContracts.ts
- resources/ts/layouts/AdminLayout.tsx
- resources/ts/pages/Admin/Account.tsx
- routes/api.php
- tests/Feature/AuthTest.php
This pull request introduces several new features and improvements to the account management functionality, including token management, better error handling, and various UI enhancements. The most important changes include adding methods to list and revoke tokens, updating the login token generation, improving error messages, and enhancing the user interface for account settings.
* Added `listTokens` and `revokeToken` methods to the `AccountController` to manage user tokens (`app/Http/Controllers/Api/Admin/AccountController.php`).
* Updated login token generation to use the user agent string (`app/Http/Controllers/Api/AuthController.php`).
* Improved error message for unauthenticated requests (`bootstrap/app.php`).
* Enhanced Axios client to handle 401 errors by redirecting to the login …
> refactor: account and new tokens section

- app/Http/Controllers/Api/Admin/ZoneController.php
- resources/ts/api/service/mapService.ts
- resources/ts/api/service/zoneService.ts
- resources/ts/components/Map.tsx
- resources/ts/types/Zone.ts
- routes/api.php
Reverts Projecte-UrbanTree/application#346
> Revert "Add getCenterZoom endpoint and integrate with map services"

- resources/ts/api/service/mapService.ts
- resources/ts/components/Map.tsx
- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/layouts/AdminLayout.tsx
- resources/ts/pages/Admin/Inventory/EditElementForm.tsx
- resources/ts/pages/Admin/Inventory/ElementComponent.tsx
- resources/ts/pages/Admin/Inventory/ElementDetailPopup.tsx
- resources/ts/pages/Admin/Inventory/IncidentForm.tsx
- resources/ts/pages/Admin/Inventory/Index.tsx
- resources/ts/pages/Admin/Inventory/SaveElementForm.tsx
- resources/ts/pages/Admin/Inventory/SaveZoneForm.tsx
- resources/ts/pages/Admin/Inventory/Zones.tsx
This pull request focuses on enhancing the `MapService` class and the `MapComponent` in a TypeScript project. The changes include adding error handling, optimizing condition checks, and improving code readability.
Improvements to `MapService` class:
* Added error handling in methods like `removeDraw`, `clearDraw`, `removeLayersAndSources`, `addZoneToMap`, `flyTo`, and `resetMap` to ensure the map operations do not fail silently. [[1]](diffhunk://#diff-087dbd3207f44a8047f8087446874c65e1b1fc383c1f0096368edbb83f18925aR91-R132) [[2]](diffhunk://#diff-087dbd3207f44a8047f8087446874c65e1b1fc383c1f0096368edbb83f18925aL128-R167) [[3]](diffhunk://#diff-087dbd3207f44a8047f8087446874c65e1b1fc383c1f0096368edbb83f18925aR188-R225) [[4]](diffhunk://#diff-087dbd3207f44a8047f8087446874c65e1b1fc383c1f0096368 …
> refactor: enchance styles of map

- app/Http/Controllers/Api/Admin/ElementController.php
- app/Http/Controllers/Api/Admin/EvaController.php
- app/Http/Controllers/Api/Admin/ZoneController.php
- resources/ts/api/service/zoneService.ts
- resources/ts/components/Map.tsx
- resources/ts/components/Preloader.tsx
- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/hooks/useAuth.ts
- resources/ts/layouts/AdminLayout.tsx
- resources/ts/pages/Admin/Dashboard/Components/InProgressWorkOrders.tsx
- resources/ts/pages/Admin/Dashboard/Index.tsx
- resources/ts/pages/Admin/Inventory/EditElementForm.tsx
- resources/ts/pages/Admin/Inventory/ElementComponent.tsx
- resources/ts/pages/Admin/Inventory/ElementDetailPopup.tsx
- resources/ts/pages/Admin/Inventory/IncidentForm.tsx
- resources/ts/pages/Admin/Inventory/Index.tsx
- resources/ts/pages/Admin/Inventory/SaveElementForm.tsx
- resources/ts/pages/Admin/Inventory/SaveZoneForm.tsx
- resources/ts/pages/Admin/Inventory/Zones.tsx
- resources/ts/pages/Logout.tsx
- routes/api.php
This pull request includes several changes across multiple files to improve functionality and user experience, particularly in the handling of elements, zones, and translations. The most important changes include adding a new inline update feature for zones, modifying the element type validation, updating the map component, and enhancing the preloader.
* [`app/Http/Controllers/Api/Admin/ZoneController.php`](diffhunk://#diff-7460e4459f33f9139e3fdd5db0500d502a5b11fdfd37a34ac0d1712119f6182bR68-R87): Added `inlineUpdate` method to allow inline updates for zone name or description.
* [`resources/ts/api/service/zoneService.ts`](diffhunk://#diff-815e0a99f0eac72ddb4a8d64d0e97869635a2d425c89b737da3e992a525a554bR25-R29): Added `inlineUpdateZone` function to support the new inline update feature.
* …
> refactor: a lot of changes on map, layout and logout

- app/Http/Controllers/Api/Admin/ElementController.php
- resources/ts/components/Map.tsx
- resources/ts/pages/Admin/Inventory/Zones.tsx
This update modifies the `destroy` method in the `ElementController` to ensure that all related incidences are deleted when an element is removed. Additionally, if the element has an associated evaluation, it will also be deleted.
In the `MapComponent`, success toast notifications for element deletion have been removed to streamline the user experience.
Minor adjustments were made in the `Zones` component to maintain code consistency.
> feat: enhance element deletion process by removing associated incident

- resources/ts/config/i18n/ca.json
- resources/ts/config/i18n/en.json
- resources/ts/config/i18n/es.json
- resources/ts/pages/Admin/Sensor/Index.tsx
- resources/ts/pages/Admin/Sensor/Show.tsx
This pull request introduces enhancements to the sensor history page and updates localization files. The most significant changes include the addition of a new "Day" label to localization files, improvements to data aggregation and chart rendering, and better handling of missing data in the sensor history table.
* Added a new "Day" label to the localization files for Catalan, English, and Spanish (`ca.json`, `en.json`, `es.json`). [[1]](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85L1602-R1603) [[2]](diffhunk://#diff-75fa9e3a78347c6cd6a747ef879348f248881628a32d8926eba7a5036998bba3L1597-R1598) [[3]](diffhunk://#diff-db19a2b522ebee2953f9c96329f0090c6e63dc155903585c7b618220ad3998a6L1601-R1602)
* Updated the sensor history logic to group data by day and …
> Fix(sensorhistory): metrics available
