Projecte-UrbanTree/application

.github/workflows/laravel.yml
This pull request includes changes to the GitHub Actions workflow for Laravel to enhance the setup and testing process. The most important changes include renaming a job step, adding steps to install Node.js and NPM dependencies, and building frontend assets.
Enhancements to the workflow:
* [`.github/workflows/laravel.yml`](diffhunk://#diff-780598065d009a102c43b543e7f6670ce1d9029b6ddb86dc98cb1a94433cccb1L11-R20): Renamed the job step from "Install Dependencies" to "Install PHP Dependencies" for clarity.
* [`.github/workflows/laravel.yml`](diffhunk://#diff-780598065d009a102c43b543e7f6670ce1d9029b6ddb86dc98cb1a94433cccb1R30-R35): Added steps to install Node.js, install NPM dependencies, and build frontend assets to ensure the frontend is properly set up before running tests.
=> fix: add assets building in tests workflow

.env.example, README.md, docker-compose.yml
This pull request includes a small but important change to the `README.md` file. The change updates the instructions for setting up the development environment in a dev container.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L32-R32): Modified the setup instructions to include running `composer setup` after the dev container starts.
=> refactor: update missing step on README.md

.devcontainer/devcontainer.json
This pull request includes a small but important change to the `.devcontainer/devcontainer.json` file. The change adds a new feature to the development container configuration to enable the Git credential helper.
* [`.devcontainer/devcontainer.json`](diffhunk://#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686L5-R10): Added the `ghcr.io/devcontainers/features/git:1` feature with the `enableGitCredentialHelper` option set to true.
=> feat: devcontainer now using ssh keys from host machine

app/Models/WorkOrderBlockTask.php
This pull request includes a small but important change to the `app/Models/WorkOrderBlockTask.php` file. The change ensures that the `tasksTypes` method returns the correct relationship.
* [`app/Models/WorkOrderBlockTask.php`](diffhunk://#diff-4f444250a6dac5ffb10e5a34f9e6357cc80afaca2147ec47a291f6f6637884f3L30-R30): Modified the `tasksTypes` method to return a `belongsTo` relationship with the `TaskType` class instead of the `Task` class.
=> fix(models): correct relationship reference in WorkOrderBlockTask for task type

database/seeders/UserSeeder.php
This pull request includes changes to the `database/seeders/UserSeeder.php` file to correct the field name for user entries. The `username` field has been updated to `surname` for all user records.
Changes to `database/seeders/UserSeeder.php`:
* Updated the field `username` to `surname` for user 'Gemma'
* Updated the field `username` to `surname` for user 'Worker 1'
* Updated the field `username` to `surname` for user 'Worker 2'
* Updated the field `username` to `surname` for user 'Customer'
=> refactor(seeder): rename 'username' to 'surname' in UserSeeder

app/Http/Controllers/LangController.php, app/Http/Middleware/LanguageMiddleware.php, app/Providers/AppServiceProvider.php, package-lock.json, package.json, resources/ts/config/i18n.ts, resources/ts/hooks/useI18n.ts
This pull request includes several changes aimed at transitioning the language preference storage from `localStorage` to cookies, and updating dependencies accordingly. The most important changes include modifications to the `LangController`, `LanguageMiddleware`, and `AppServiceProvider` classes, as well as updates to the `i18n` configuration and the addition of a new dependency in `package.json`.
* [`app/Http/Controllers/LangController.php`](diffhunk://#diff-a47e65e974ad99e452777cc9a034d22d331bc2a380516b18f9edff7a3a2338c8L13-R13): Updated the `setLanguage` method to use `Cookie::make` for setting the language cookie instead of `Cookie::queue`.
* [`app/Http/Middleware/LanguageMiddleware.php`](diffhunk://#diff-4dd3808bc5cecc4f539225f83f28ed3321dca981629ca21c7f31b6e26daa9118L19-R20): …
=> refactor: sync sites langs

resources/css/app.css
This pull request includes a small change to the `resources/css/app.css` file. The change adjusts the background color opacity of the `#app` element from 0.9 to 0.85.
=> refactor: adjust background color opacity for #app

bootstrap/app.php
This pull request includes a change to the `bootstrap/app.php` file to simplify the middleware configuration by removing the CSRF token validation exclusion for API routes.
Simplification of middleware configuration:
* [`bootstrap/app.php`](diffhunk://#diff-10bc2462d34ebc59a5d482a1faca04ce74f6df89fcc2ef8bfb17b939647ea518L18-L20): Removed the CSRF token validation exclusion for API routes to streamline the middleware setup.
=> refactor: restore CSRF token validation for API middleware

app/Http/Controllers/LandingController.php, resources/views/Landings/landing11.blade.php, routes/web.php
This pull request includes changes to the `LandingController` and related routes and views to support dynamic landing page numbers. The most important changes include modifying the controller methods to accept a `number` parameter, updating the routes to use dynamic segments, and adjusting the form action in the view.
Changes to `LandingController`:
* [`app/Http/Controllers/LandingController.php`](diffhunk://#diff-3eaa8a20c34668a2a5c7fa5e355631ec940d9841311359def89a413b3212c31eL10-R18): Modified the `index` and `store` methods to accept an `int $number` parameter and updated the view and redirect paths to use this dynamic number. [[1]](diffhunk://#diff-3eaa8a20c34668a2a5c7fa5e355631ec940d9841311359def89a413b3212c31eL10-R18) [[2]](diffhunk://#diff-3eaa8a20c34668a2a5c7fa5e355631ec940d9841311 …
=> refactor: make landing routes dynamic and update form handling

lang/ca/landings/landing9.php
This pull request includes a small change to the `lang/ca/landings/landing9.php` file. The change updates the `video_url` in the call-to-action section.
* [`lang/ca/landings/landing9.php`](diffhunk://#diff-6764d62127c474c2109938ca4db5445b20365754fad1146a4b587763c8b43462L60-R60): Updated the `video_url` from 'https://www.youtube.com/embed/M0VBcCEp10E' to 'https://www.youtube.com/embed/3eCPW5mGKhw'.
=> fix: update video URL for Urban Tree introduction on landing 9 (catalan)

resources/ts/config/i18n/ca.json, resources/ts/config/i18n/en.json, resources/ts/config/i18n/es.json
This pull request includes updates to the internationalization (i18n) configuration files to add a new translation entry for "EVA" across multiple languages.
Updates to i18n configuration:
* [`resources/ts/config/i18n/ca.json`](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85R490): Added the translation entry for "EVA" in Catalan.
* [`resources/ts/config/i18n/en.json`](diffhunk://#diff-75fa9e3a78347c6cd6a747ef879348f248881628a32d8926eba7a5036998bba3R490): Added the translation entry for "EVA" in English.
* [`resources/ts/config/i18n/es.json`](diffhunk://#diff-db19a2b522ebee2953f9c96329f0090c6e63dc155903585c7b618220ad3998a6R490): Added the translation entry for "EVA" in Spanish.
=> feat(i18n): add translation for "eva" in Catalan, English, and Spanish

resources/ts/pages/Admin/Settings/Contracts/Contracts.tsx
This pull request includes changes to the `Contracts` component in the `resources/ts/pages/Admin/Settings/Contracts/Contracts.tsx` file. The main focus is on refactoring how contract status is handled and displayed.
Refactoring contract status handling:
* Removed the `statusOptions` array and replaced it with a `switch` statement to handle different contract statuses directly in the JSX. This change simplifies the code and improves readability.
* Updated the `Column` component for the `status` field to use the new `switch` statement, ensuring that the correct badge with the appropriate label and severity is displayed based on the contract status.
=> feat(contracts): refactor status display logic in Contracts component

.github/workflows/deploy-production.yml
This pull request includes a single change to the deployment process in the `deploy-production.yml` workflow file. The change modifies the SSH command to use a specific port for the connection.
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94L53-R53): Updated the `rsync` command to use port `21222` for SSH connections.
=> feat(ci): update SSH port in production deployment workflow

.github/workflows/deploy-production.yml
This pull request includes a small change to the `.github/workflows/deploy-production.yml` file. The change adds a command to update the package list and install `sshpass`, and modifies the `rsync` command to include additional options for permissions and group handling.
Changes in deployment workflow:
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94R54-R57): Added `sudo apt-get update && sudo apt-get install -y sshpass` to the `run` section to ensure `sshpass` is installed.
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94R54-R57): Modified the `rsync` command to include `--no-perms`, `--no-group`, and `--chmod=ugo=rwX` options for …
=> feat: update workflow permissions

.github/workflows/deploy-production.yml
This pull request includes a small but important change to the `deploy-production` workflow. The change ensures that sensitive and unnecessary files are excluded during the deployment process.
* [`.github/workflows/deploy-production.yml`](diffhunk://#diff-99ce179d261b73100b5672f064452b508820755c8e043e7ea4de36b9ec943d94R57): Added `.env` and `database/database.sqlite` to the list of excluded files during the rsync operation to prevent sensitive data from being transferred.
=> chore: exclude additional files from production deployment

.github/workflows/deploy-production.yml
This pull request includes changes to the deployment script in the `.github/workflows/deploy-production.yml` file to improve security and add new steps for dependency installation.
Security improvement:
* Modified the deployment script to use `echo "$SSH_PASSWORD" | sudo -S` for all `sudo` commands to avoid interactive password prompts and ensure the commands can run in a non-interactive environment.
New steps for dependency installation:
* Added commands to install PHP and Node.js dependencies using `composer install`, `npm install`, and `npm run build`.
=> chore: update deployment workflow to use SSH password for commands

app/Models/User.php, database/migrations/0001_01_01_000000_create_users_table.php, database/seeders/UserSeeder.php
This pull request introduces changes to the `User` model, database migrations, and seeders to incorporate a new relationship with the `Contract` model. The most important changes include adding a new `contract_id` field to the `users` table and updating the `User` model to define this relationship.
Changes to the `User` model:
* Added the `contract_id` field to the `$fillable` array in the `User` model (`app/Models/User.php`).
* Added a new `contract` method to define the relationship between `User` and `Contract` models (`app/Models/User.php`).
Changes to database migrations:
* Added a `contract_id` foreign key to the `users` table in the `create_users_table` migration (`database/migrations/0001_01_01_000000_create_users_table.php`).
Changes to database seeders:
* Updated the …
=> feat: add contract_id to User model and migration, update UserSeeder

app/Http/Controllers/Api/Admin/WorkOrderController.php, database/seeders/DatabaseSeeder.php, database/seeders/UserSeeder.php, resources/ts/layouts/AdminLayout.tsx, resources/ts/pages/Admin/WorkOrders/Create.tsx, resources/ts/pages/Admin/WorkOrders/Edit.tsx, resources/ts/pages/Admin/WorkOrders/WorkOrders.tsx
This pull request includes several changes to the `WorkOrderController`, seeders, and frontend components to improve the handling of contracts in work orders. The most important changes include updating the `create` and `update` methods in the `WorkOrderController`, modifying the `DatabaseSeeder` and `UserSeeder` classes, and enhancing the frontend logic in `AdminLayout`, `CreateWorkOrder`, `EditWorkOrder`, and `WorkOrders` components.
* [`app/Http/Controllers/Api/Admin/WorkOrderController.php`](diffhunk://#diff-caef59b26d7256d70e5cc9452f7c58530c1ec841f904874ae1bcccd7a6e994e8R38-R50): Modified the `create` method to filter `users` and `zones` by `contract_id` if provided, and removed the `contract_id` requirement from the `update` method. …
=> feat: add contract filtering to work orders and update related components

resources/ts/hooks/useAuth.ts
This pull request includes a small change to the `useAuth` function in the `resources/ts/hooks/useAuth.ts` file. The change removes the dependency on `user.id` from the `useEffect` dependency array, ensuring that the effect only runs once when the component mounts.
* [`resources/ts/hooks/useAuth.ts`](diffhunk://#diff-fb7e7abb5d7fb941eb83fe9e93759edd8ba87c45ff771a5fb97795f8d9c12418L22-R22): Removed `user.id` from the dependency array in the `useEffect` hook to ensure the effect only runs on mount.
=> fix(auth): remove unnecessary dependency from useEffect in useAuth hook

resources/ts/config/i18n/ca.json, resources/ts/config/i18n/es.json
This pull request includes updates to the Catalan and Spanish translations in the `resources/ts/config/i18n` directory. The changes ensure that the translations are accurate and consistent.
Updates to Catalan translations:
* [`resources/ts/config/i18n/ca.json`](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85L211-R213): Corrected translations for several resource-related messages, including "unit cost", "unit name", and "export to CSV". [[1]](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85L211-R213) [[2]](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85L227-R228) [[3]](diffhunk://#diff-3822e87aba8184976f5aaf0175f134591a0a92a8e8637f20c19f249a71167a85L298-R298)
Updates to Spanish …
=> fix: translations

resources/ts/pages/Admin/WorkOrders/WorkOrders.tsx
This pull request includes changes to the `WorkOrders` component in the `resources/ts/pages/Admin/WorkOrders/WorkOrders.tsx` file. The main objective of these changes is to enhance the action buttons' behavior based on the status of the work order.
Key changes include:
* Added new conditions to determine if the work order is editable or if the report can be viewed based on the status of the work order.
* Updated the rendering logic to conditionally display the edit and delete buttons only if the work order is editable.
* Updated the rendering logic to conditionally display the view report button if the work order status allows viewing the report.
=> Feat: workorder disable edit

resources/ts/components/FuncionesEva.tsx, resources/ts/pages/Admin/Eva/Create.tsx, resources/ts/pages/Admin/Eva/Edit.tsx, resources/ts/pages/Admin/Eva/Eva.tsx, resources/ts/pages/Admin/Eva/Show.tsx
This pull request includes changes to the `CreateEva` and `EditEva` components in the `resources/ts/pages/Admin/Eva` directory. The primary focus is on standardizing the naming conventions for various properties related to tree evaluation.
Changes to property names:
* [`resources/ts/pages/Admin/Eva/Create.tsx`](diffhunk://#diff-b30b98d2dc1faf654fe890519fc7dae76bfbd20404d1fb29ea0f4e3ccada5557R213-R221): Added new properties with standardized names (`unbalanced_crown`, `overextended_branches`, `dead_branches`, `V_forks`, `bark_damage`, `soil_lifting`, `cut_damaged_roots`, `basal_rot`, `exposed_surface_roots`).
* [`resources/ts/pages/Admin/Eva/Edit.tsx`](diffhunk://#diff-ca051ea54ec3a20d11aa184cc27b37287f67aae0090f7cf49f6582b267702cfbL138-R149): Updated initial state and status calculation …
=> fix: standardize variable naming for EVA attributes

app/Http/Controllers/Api/Admin/ZoneController.php, resources/ts/api/service/mapService.ts, resources/ts/api/service/zoneService.ts, resources/ts/components/Map.tsx, resources/ts/types/Zone.ts, routes/api.php
This commit introduces a new API endpoint to retrieve the center coordinates and zoom level for a specified zone. The MapService and MapComponent have been updated to utilize this new functionality, allowing for dynamic zoom adjustments based on zone delimiters. Additionally, the Zone model has been modified to include a zoom property.
=> Add getCenterZoom endpoint and integrate with map services

resources/ts/components/Map.tsx
This pull request includes changes to the `MapComponent` in the `resources/ts/components/Map.tsx` file, focusing on improving the handling of event subscriptions and ensuring proper usage of the `mapServiceRef` reference.
Improvements to event handling:
* Updated the subscription to `eventSubject` to ensure the `mapServiceRef` is correctly referenced when handling `ZoneEvent` updates.
Refactoring for clarity and safety:
* Modified the logic for disabling single click to use `mapServiceRef.current` directly, ensuring the reference is always checked before calling `disableSingleClick`.
=> fix: improve event subscription handling in MapComponent

app/Http/Controllers/Api/Admin/SensorController.php, app/Http/Controllers/Api/Admin/SensorHistoryController.php
This pull request updates API endpoint URLs in several methods across two controllers to use HTTPS instead of HTTP, ensuring secure communication with the external API.
* `app/Http/Controllers/Api/Admin/SensorController.php`:
- Updated the URL in the `show($eui)` method to use HTTPS for fetching sensor history.
- Updated the URL in the `fetchSensors()` method to use HTTPS for retrieving all sensors.
- Updated the URL in the `fetchSensorByEUI($eui)` method to use HTTPS for fetching a sensor by its EUI.
- Updated the URL in the `fetchAllHistorySensorbyEUI($eui)` method to use HTTPS for retrieving all history data for a sensor by its EUI.
* `app/Http/Controllers/Api/Admin/SensorHistoryController.php`:
- Updated the URL in the `fetchAndStoreSensorData($eui)` method to use HTTPS for fetching …
=> fix: update api url
